# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        http_version: '2.0'
        scoped_clients:
            # only requests matching scope will use these options
            openweather:
                scope: 'http://api.openweathermap.org'
                headers:
                    Accept: 'application/json'
                base_uri: 'http://api.openweathermap.org'
                query:
                    key: 'appid'
                    value: "%env(OPENWEATHERMAP_ID)%"

            # using base_uri, relative URLs (e.g. request("GET", "/repos/symfony/symfony-docs"))
            # will default to these options
            apifirst:
                base_uri: 'https://api.first.org'
                headers:
                    Accept: 'application/json'
                query:
                    key: 'access'
                    value: 'full'

    #csrf_protection: true
    #http_method_override: true
    secret: '%env(APP_SECRET)%'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
